package org.firstinspires.ftc.teamcode;

/**
 * GENERATED by tools/shots (node tools/shots/export.js). Do not edit by hand: change tools/shots/inputs.json
 * and regenerate. Rows are distance to the near lip, columns are radial robot velocity (positive closing).
 * Inputs: {"ball":"POLLEN","ballDiameterM":0.0711,"ballMassKg":0.0249,"dragCd":0.45,"launchAngleDeg":60,"exitHeightM":0.4,"exitSpeedPerRpm":0.0023,"shooterOffsetM":0.15,"rpmToleranceRpm":50,"lipHeightM":1.359,"openingWidthM":0.508,"openingLengthM":0.356,"openingTiltDeg":30,"marginM":0.02,"distMinM":0.6,"distMaxM":3,"distStepM":0.1,"velMinMps":-1,"velMaxMps":1,"velStepMps":0.1,"rpmMin":1500,"rpmMax":5500,"rpmStep":25,"dtS":0.002}
 */
public final class ShotTable {
    private ShotTable() {}

    public static final String BALL = "POLLEN";
    public static final double LAUNCH_ANGLE_DEG = 60;
    public static final double EXIT_HEIGHT_M = 0.4;
    public static final double EXIT_SPEED_PER_RPM = 0.0023;
    public static final double SHOOTER_OFFSET_M = 0.15;
    public static final double OPENING_WIDTH_M = 0.508;
    /** Ball radius plus edge margin: how far inside the opening's side edges the ball centre must pass. */
    public static final double LATERAL_CLEARANCE_M = 0.056;
    public static final double MIN_BAND_RPM = 100;
    /** The table's distances are to the near lip; the tag cluster origin is the opening centre, this far beyond it. */
    public static final double LIP_TO_CENTRE_M = 0.154;

    public static final double[] DIST_M = {0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3};
    public static final double[] VEL_MPS = {-1, -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1};
    /** Band-centre flywheel RPM, [dist][vel]. NaN where no shot lands. */
    public static final double[][] RPM = {
        {Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {2350, 2337.5, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {2400, 2375, 2350, 2350, 2350, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {2437.5, 2400, 2400, 2375, 2362.5, 2350, 2337.5, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {2475, 2450, 2425, 2400, 2387.5, 2375, 2362.5, 2350, 2337.5, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {2550, 2500, 2475, 2450, 2425, 2400, 2387.5, 2375, 2362.5, 2350, 2337.5, 2350, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {2600, 2550, 2525, 2500, 2475, 2450, 2425, 2400, 2387.5, 2375, 2362.5, 2362.5, 2350, 2337.5, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {2650, 2612.5, 2575, 2550, 2512.5, 2487.5, 2462.5, 2437.5, 2425, 2400, 2387.5, 2375, 2362.5, 2362.5, 2362.5, 2350, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {2700, 2662.5, 2625, 2600, 2562.5, 2537.5, 2500, 2475, 2462.5, 2437.5, 2425, 2400, 2387.5, 2375, 2362.5, 2362.5, 2362.5, 2362.5, 2362.5, Double.NaN, Double.NaN},
        {2750, 2712.5, 2675, 2650, 2612.5, 2575, 2550, 2525, 2500, 2475, 2450, 2437.5, 2412.5, 2400, 2387.5, 2387.5, 2362.5, 2362.5, 2362.5, 2362.5, 2362.5},
        {2812.5, 2762.5, 2737.5, 2687.5, 2662.5, 2625, 2600, 2562.5, 2537.5, 2512.5, 2487.5, 2475, 2450, 2437.5, 2412.5, 2412.5, 2387.5, 2387.5, 2375, 2362.5, 2362.5},
        {2862.5, 2812.5, 2787.5, 2737.5, 2712.5, 2675, 2637.5, 2612.5, 2587.5, 2562.5, 2537.5, 2512.5, 2487.5, 2462.5, 2450, 2437.5, 2412.5, 2412.5, 2387.5, 2387.5, 2387.5},
        {2912.5, 2875, 2837.5, 2787.5, 2762.5, 2725, 2687.5, 2662.5, 2637.5, 2600, 2575, 2550, 2525, 2512.5, 2487.5, 2462.5, 2450, 2437.5, 2412.5, 2412.5, 2387.5},
        {2962.5, 2925, 2887.5, 2837.5, 2812.5, 2762.5, 2737.5, 2712.5, 2675, 2637.5, 2612.5, 2587.5, 2562.5, 2537.5, 2512.5, 2500, 2487.5, 2462.5, 2437.5, 2437.5, 2412.5},
        {3012.5, 2987.5, 2937.5, 2887.5, 2862.5, 2812.5, 2787.5, 2762.5, 2712.5, 2687.5, 2662.5, 2637.5, 2612.5, 2587.5, 2562.5, 2537.5, 2512.5, 2487.5, 2487.5, 2462.5, 2437.5},
        {3062.5, 3037.5, 2987.5, 2937.5, 2912.5, 2862.5, 2837.5, 2787.5, 2762.5, 2737.5, 2712.5, 2675, 2637.5, 2612.5, 2587.5, 2562.5, 2550, 2537.5, 2512.5, 2487.5, 2475},
        {3125, 3087.5, 3037.5, 2987.5, 2962.5, 2912.5, 2887.5, 2837.5, 2812.5, 2787.5, 2737.5, 2712.5, 2687.5, 2662.5, 2637.5, 2612.5, 2587.5, 2562.5, 2537.5, 2525, 2512.5},
        {3175, 3137.5, 3087.5, 3037.5, 3012.5, 2962.5, 2937.5, 2887.5, 2862.5, 2812.5, 2787.5, 2762.5, 2737.5, 2712.5, 2687.5, 2637.5, 2625, 2612.5, 2587.5, 2562.5, 2537.5},
        {3225, 3187.5, 3137.5, 3087.5, 3062.5, 3012.5, 2975, 2937.5, 2912.5, 2862.5, 2837.5, 2812.5, 2762.5, 2737.5, 2712.5, 2687.5, 2662.5, 2637.5, 2612.5, 2587.5, 2562.5},
        {3275, 3237.5, 3187.5, 3137.5, 3100, 3062.5, 3025, 2987.5, 2950, 2912.5, 2887.5, 2837.5, 2812.5, 2787.5, 2762.5, 2737.5, 2712.5, 2687.5, 2662.5, 2637.5, 2612.5},
        {3325, 3275, 3237.5, 3187.5, 3150, 3112.5, 3062.5, 3037.5, 2987.5, 2962.5, 2925, 2887.5, 2862.5, 2837.5, 2800, 2762.5, 2737.5, 2712.5, 2687.5, 2662.5, 2637.5},
        {3375, 3325, 3287.5, 3237.5, 3200, 3162.5, 3112.5, 3075, 3037.5, 3012.5, 2962.5, 2937.5, 2900, 2862.5, 2837.5, 2812.5, 2787.5, 2762.5, 2737.5, 2712.5, 2687.5},
        {3425, 3375, 3337.5, 3287.5, 3250, 3200, 3162.5, 3125, 3087.5, 3050, 3012.5, 2987.5, 2950, 2912.5, 2887.5, 2850, 2825, 2787.5, 2762.5, 2737.5, 2712.5},
        {3475, 3425, 3375, 3337.5, 3300, 3250, 3212.5, 3175, 3137.5, 3100, 3062.5, 3025, 2987.5, 2962.5, 2925, 2887.5, 2862.5, 2837.5, 2812.5, 2787.5, 2762.5},
        {3525, 3475, 3425, 3387.5, 3337.5, 3300, 3262.5, 3212.5, 3175, 3137.5, 3100, 3062.5, 3037.5, 3000, 2962.5, 2937.5, 2912.5, 2875, 2850, 2812.5, 2787.5}
    };
    /** Width of the valid RPM band, [dist][vel]. NaN where no shot lands. */
    public static final double[][] BAND_RPM = {
        {75, 0, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {150, 125, 75, 25, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {150, 150, 150, 150, 100, 25, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {175, 150, 150, 150, 125, 150, 125, 50, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {150, 150, 150, 150, 125, 150, 125, 150, 125, 75, 0, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {150, 150, 150, 150, 150, 150, 125, 150, 125, 150, 125, 100, 25, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {150, 150, 150, 150, 150, 150, 150, 150, 125, 150, 125, 125, 150, 125, 50, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {150, 125, 150, 150, 125, 125, 125, 125, 150, 150, 125, 150, 125, 125, 125, 100, 75, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {150, 125, 150, 150, 125, 125, 150, 150, 125, 125, 150, 150, 125, 150, 125, 125, 125, 125, 125, 25, Double.NaN},
        {150, 125, 150, 150, 125, 150, 150, 150, 150, 150, 150, 125, 125, 150, 125, 125, 125, 125, 125, 125, 125},
        {125, 125, 125, 125, 125, 150, 150, 125, 125, 125, 125, 150, 150, 125, 125, 125, 125, 125, 150, 125, 125},
        {125, 125, 125, 125, 125, 150, 125, 125, 125, 125, 125, 125, 125, 125, 150, 125, 125, 125, 125, 125, 125},
        {125, 150, 125, 125, 125, 150, 125, 125, 125, 150, 150, 150, 150, 125, 125, 125, 150, 125, 125, 125, 125},
        {125, 150, 125, 125, 125, 125, 125, 125, 150, 125, 125, 125, 125, 125, 125, 150, 125, 125, 125, 125, 125},
        {125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125},
        {125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 150, 125, 125, 125, 125, 150, 125, 125, 125, 150},
        {100, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 150, 125},
        {100, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 150, 125, 125, 125, 125},
        {100, 125, 125, 125, 125, 125, 100, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125},
        {100, 125, 125, 125, 100, 125, 100, 125, 100, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125, 125},
        {100, 100, 125, 125, 100, 125, 125, 125, 125, 125, 100, 125, 125, 125, 100, 125, 125, 125, 125, 125, 125},
        {100, 100, 125, 125, 100, 125, 125, 100, 125, 125, 125, 125, 100, 125, 125, 125, 125, 125, 125, 125, 125},
        {100, 100, 125, 125, 100, 100, 125, 100, 125, 100, 125, 125, 100, 125, 125, 100, 100, 125, 125, 125, 125},
        {100, 100, 100, 125, 100, 100, 125, 100, 125, 100, 125, 100, 125, 125, 100, 125, 125, 125, 125, 125, 125},
        {100, 100, 100, 125, 125, 100, 125, 125, 100, 125, 100, 125, 125, 100, 125, 125, 125, 100, 100, 125, 125}
    };
    /** Time of flight at the band centre, seconds, [dist][vel]. */
    public static final double[][] TOF_S = {
        {Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {0.518, 0.492, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {0.572, 0.546, 0.518, 0.5, 0.48, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {0.612, 0.584, 0.568, 0.544, 0.522, 0.5, 0.476, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {0.648, 0.626, 0.604, 0.58, 0.562, 0.542, 0.522, 0.502, 0.48, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {0.69, 0.662, 0.642, 0.62, 0.6, 0.578, 0.56, 0.54, 0.522, 0.502, 0.482, 0.47, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {0.724, 0.698, 0.678, 0.658, 0.636, 0.616, 0.596, 0.574, 0.558, 0.54, 0.522, 0.506, 0.488, 0.468, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {0.754, 0.732, 0.71, 0.69, 0.668, 0.648, 0.628, 0.608, 0.592, 0.572, 0.556, 0.538, 0.52, 0.508, 0.494, 0.476, Double.NaN, Double.NaN, Double.NaN, Double.NaN, Double.NaN},
        {0.784, 0.762, 0.742, 0.722, 0.7, 0.682, 0.66, 0.64, 0.624, 0.606, 0.59, 0.57, 0.554, 0.538, 0.52, 0.508, 0.494, 0.482, 0.468, Double.NaN, Double.NaN},
        {0.812, 0.792, 0.77, 0.752, 0.73, 0.71, 0.692, 0.672, 0.654, 0.636, 0.618, 0.602, 0.584, 0.568, 0.552, 0.54, 0.52, 0.508, 0.496, 0.484, 0.472},
        {0.844, 0.82, 0.802, 0.778, 0.76, 0.74, 0.722, 0.7, 0.682, 0.664, 0.646, 0.632, 0.614, 0.598, 0.58, 0.568, 0.55, 0.538, 0.524, 0.508, 0.498},
        {0.87, 0.846, 0.828, 0.806, 0.788, 0.768, 0.746, 0.73, 0.712, 0.694, 0.678, 0.66, 0.642, 0.624, 0.61, 0.596, 0.578, 0.568, 0.55, 0.538, 0.528},
        {0.894, 0.874, 0.854, 0.832, 0.814, 0.794, 0.774, 0.758, 0.74, 0.72, 0.704, 0.686, 0.67, 0.656, 0.638, 0.622, 0.608, 0.594, 0.576, 0.566, 0.548},
        {0.92, 0.9, 0.88, 0.858, 0.84, 0.818, 0.802, 0.784, 0.764, 0.744, 0.728, 0.712, 0.694, 0.678, 0.662, 0.648, 0.634, 0.618, 0.602, 0.59, 0.574},
        {0.944, 0.926, 0.904, 0.882, 0.866, 0.844, 0.826, 0.81, 0.788, 0.772, 0.756, 0.738, 0.722, 0.706, 0.69, 0.674, 0.658, 0.642, 0.63, 0.614, 0.598},
        {0.966, 0.95, 0.928, 0.906, 0.89, 0.868, 0.852, 0.83, 0.814, 0.798, 0.782, 0.762, 0.744, 0.728, 0.712, 0.696, 0.682, 0.67, 0.654, 0.638, 0.624},
        {0.992, 0.974, 0.952, 0.93, 0.914, 0.892, 0.876, 0.854, 0.838, 0.822, 0.8, 0.784, 0.768, 0.754, 0.738, 0.722, 0.706, 0.69, 0.674, 0.662, 0.65},
        {1.014, 0.996, 0.974, 0.952, 0.938, 0.916, 0.9, 0.878, 0.862, 0.842, 0.826, 0.81, 0.794, 0.778, 0.762, 0.742, 0.73, 0.716, 0.702, 0.686, 0.67},
        {1.036, 1.018, 0.996, 0.976, 0.96, 0.938, 0.92, 0.902, 0.886, 0.864, 0.85, 0.834, 0.812, 0.798, 0.782, 0.766, 0.752, 0.736, 0.722, 0.706, 0.692},
        {1.058, 1.04, 1.018, 0.998, 0.98, 0.962, 0.942, 0.924, 0.906, 0.888, 0.872, 0.852, 0.836, 0.822, 0.806, 0.792, 0.776, 0.76, 0.746, 0.732, 0.716},
        {1.08, 1.058, 1.04, 1.02, 1.002, 0.984, 0.962, 0.946, 0.926, 0.91, 0.892, 0.874, 0.86, 0.844, 0.828, 0.81, 0.794, 0.78, 0.764, 0.75, 0.736},
        {1.1, 1.08, 1.062, 1.04, 1.022, 1.004, 0.984, 0.966, 0.948, 0.934, 0.912, 0.898, 0.88, 0.862, 0.848, 0.832, 0.818, 0.804, 0.788, 0.774, 0.76},
        {1.12, 1.1, 1.082, 1.062, 1.044, 1.024, 1.006, 0.988, 0.97, 0.952, 0.934, 0.92, 0.902, 0.884, 0.87, 0.852, 0.838, 0.82, 0.806, 0.792, 0.778},
        {1.142, 1.12, 1.1, 1.082, 1.064, 1.044, 1.026, 1.01, 0.992, 0.974, 0.956, 0.938, 0.922, 0.906, 0.89, 0.872, 0.858, 0.844, 0.828, 0.814, 0.8},
        {1.162, 1.14, 1.12, 1.102, 1.082, 1.066, 1.048, 1.028, 1.01, 0.992, 0.976, 0.958, 0.942, 0.926, 0.908, 0.894, 0.88, 0.862, 0.848, 0.832, 0.818}
    };
}
