package org.firstinspires.ftc.teamcode;

/**
 * Turns robot pose, robot velocity and the Cell position into a flywheel RPM and a heading.
 *
 * The table (generated by tools/shots) already contains the effect of the robot's radial velocity on
 * the ball, so the only lookahead here is the indexer feed delay. Tangential velocity becomes a heading
 * lead: the robot turns away from its sideways motion so the ball's horizontal velocity (exit plus robot)
 * points at the Cell. Pure maths, no SDK types, unit tested.
 */
public final class ShotSolver {
    public static final class Shot {
        public final boolean valid;
        public final String reason;
        /** Flywheel target when valid. */
        public final double rpm;
        /** Flywheel target to hold when not valid: the stationary RPM at this distance clamped to the grid, or the fallback if that cell is empty. */
        public final double idleRpm;
        /** Field heading the robot must point to, radians. */
        public final double headingRad;
        /** Heading error allowed by the Cell width at this distance, radians. */
        public final double headingToleranceRad;
        /** Distance to the Cell's near lip, matching the table's distance axis (targetX/targetY is the opening centre). */
        public final double distanceM;
        public final double radialVel;
        public final double tangentialVel;
        public final double timeOfFlightS;
        public final double bandRpm;

        Shot(boolean valid, String reason, double rpm, double idleRpm, double headingRad, double headingToleranceRad,
             double distanceM, double radialVel, double tangentialVel, double timeOfFlightS, double bandRpm) {
            this.valid = valid;
            this.reason = reason;
            this.rpm = rpm;
            this.idleRpm = idleRpm;
            this.headingRad = headingRad;
            this.headingToleranceRad = headingToleranceRad;
            this.distanceM = distanceM;
            this.radialVel = radialVel;
            this.tangentialVel = tangentialVel;
            this.timeOfFlightS = timeOfFlightS;
            this.bandRpm = bandRpm;
        }

        /** How far to turn, radians, positive to the left (anticlockwise). */
        public double headingErrorRad(double currentHeadingRad) {
            return wrap(headingRad - currentHeadingRad);
        }
    }

    private final double[] dist;
    private final double[] vel;
    private final double[][] rpm;
    private final double[][] band;
    private final double[][] tof;
    private final double launchAngleRad;
    private final double exitSpeedPerRpm;
    private final double shooterOffsetM;
    private final double lipToCentreM;
    private final double feedDelayS;
    private final double minBandRpm;
    private final double halfOpeningM;
    private final double fallbackRpm;

    public ShotSolver(double[] dist, double[] vel, double[][] rpm, double[][] band, double[][] tof,
                      double launchAngleDeg, double exitSpeedPerRpm, double shooterOffsetM, double lipToCentreM,
                      double feedDelayS, double minBandRpm, double openingWidthM, double lateralClearanceM,
                      double fallbackRpm) {
        this.dist = dist;
        this.vel = vel;
        this.rpm = rpm;
        this.band = band;
        this.tof = tof;
        this.launchAngleRad = Math.toRadians(launchAngleDeg);
        this.exitSpeedPerRpm = exitSpeedPerRpm;
        this.shooterOffsetM = shooterOffsetM;
        this.lipToCentreM = lipToCentreM;
        this.feedDelayS = feedDelayS;
        this.minBandRpm = minBandRpm;
        this.halfOpeningM = openingWidthM / 2 - lateralClearanceM;
        this.fallbackRpm = fallbackRpm;
    }

    /**
     * @param x, y, headingRad robot pose, field frame, metres and radians
     * @param vx, vy           robot velocity, field frame, m/s
     * @param targetX, targetY Cell opening centre, field frame (what TargetTracker reports)
     */
    public Shot solve(double x, double y, double headingRad, double vx, double vy, double targetX, double targetY) {
        // 1. Where the robot will be when the ball leaves.
        double px = x + vx * feedDelayS;
        double py = y + vy * feedDelayS;
        // 2. Where the ball leaves from.
        double sx = px + shooterOffsetM * Math.cos(headingRad);
        double sy = py + shooterOffsetM * Math.sin(headingRad);
        double dx = targetX - sx;
        double dy = targetY - sy;
        double d = Math.hypot(dx, dy);
        double bearing = Math.atan2(dy, dx);
        // 3. Robot velocity along and across the line to the Cell, from the un-shortened distance.
        double ux = dx / d;
        double uy = dy / d;
        double radial = vx * ux + vy * uy;
        double tangential = -vx * uy + vy * ux;
        // The table's distance axis is to the Cell's near lip; the Cell tag gives the opening centre.
        d -= lipToCentreM;
        // 4. Table lookup.
        double tableRpm = interpolate(dist, vel, rpm, d, radial);
        double tableBand = interpolate(dist, vel, band, d, radial);
        double tableTof = interpolate(dist, vel, tof, d, radial);
        double stationary = interpolate(dist, vel, rpm, Math.max(dist[0], Math.min(dist[dist.length - 1], d)), 0);
        double idle = Double.isNaN(stationary) ? fallbackRpm : stationary;
        double tolerance = Math.atan(halfOpeningM / d);

        // 5. Horizontal exit speed, needed both to gate the shot and (below) to compute the lead.
        // cos(90 deg) in doubles is ~6e-17, not exactly zero, so an unguarded ratio would clamp to a
        // bogus +-90 deg lead instead of rejecting the shot; the epsilon below catches that and NaN.
        double horizontalExit = tableRpm * exitSpeedPerRpm * Math.cos(launchAngleRad);

        String reason = "OK";
        if (d < dist[0] || d > dist[dist.length - 1]) reason = "OUT OF RANGE";
        else if (radial > vel[vel.length - 1]) reason = "CLOSING TOO FAST";
        else if (radial < vel[0]) reason = "BACKING TOO FAST";
        else if (Double.isNaN(tableRpm) || Double.isNaN(tableBand) || Double.isNaN(tableTof)
                || tableBand < minBandRpm || !(horizontalExit > 1e-6)) reason = "NO SHOT";
        if (!reason.equals("OK")) {
            return new Shot(false, reason, Double.NaN, idle, bearing, tolerance, d, radial, tangential, Double.NaN, tableBand);
        }
        // 6. Heading lead so exit velocity plus robot velocity points along the bearing.
        double lead = Math.asin(Math.max(-1, Math.min(1, tangential / horizontalExit)));
        return new Shot(true, reason, tableRpm, idle, wrap(bearing - lead), tolerance, d, radial, tangential, tableTof, tableBand);
    }

    /** Bilinear interpolation on a grid v[xIndex][yIndex]. NaN outside the grid or beside a NaN corner. */
    static double interpolate(double[] xs, double[] ys, double[][] v, double x, double y) {
        if (x < xs[0] || x > xs[xs.length - 1] || y < ys[0] || y > ys[ys.length - 1]) return Double.NaN;
        int i = upperIndex(xs, x);
        int j = upperIndex(ys, y);
        double tx = (x - xs[i - 1]) / (xs[i] - xs[i - 1]);
        double ty = (y - ys[j - 1]) / (ys[j] - ys[j - 1]);
        double a = v[i - 1][j - 1], b = v[i][j - 1], c = v[i - 1][j], e = v[i][j];
        if (Double.isNaN(a) || Double.isNaN(b) || Double.isNaN(c) || Double.isNaN(e)) return Double.NaN;
        double low = a + (b - a) * tx;
        double high = c + (e - c) * tx;
        return low + (high - low) * ty;
    }

    /** Index i in [1, n-1] with axis[i-1] <= value <= axis[i]. */
    private static int upperIndex(double[] axis, double value) {
        int i = 1;
        while (i < axis.length - 1 && axis[i] < value) i++;
        return i;
    }

    /** Wraps an angle to (-pi, pi]. */
    static double wrap(double rad) {
        double r = rad % (2 * Math.PI);
        if (r <= -Math.PI) r += 2 * Math.PI;
        if (r > Math.PI) r -= 2 * Math.PI;
        return r;
    }
}
